### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by RyanRamchandar** [rinukkusu/darksky-weather-dart#10]
Now that Flutter 2.0 and Dart 2.12 are out, this package should be migrated to sound null safety to not block apps that also want to upgrade to null safety.

**Comment by douglasbianchi** [comment]
Is there a timeline for this? I just broke my project upgrading to flutter 2.0  😅

**Comment by RyanRamchandar** [comment]
@rinukkusu any updates on this?

**Comment by rinukkusu** [comment]
To be honest with you guys I didn't have the time to catch up with new dart features yet, since I'm not using it at work anymore. If you know what to do, please create a PR as I can't promise you when I'll get to it. 😞

**Comment by RyanRamchandar** [comment]
Fixed in #11
