### ISSUE TITLE
Upgrade for json_annotation 3.0.0?

### ISSUE THREAD

**Issue by sowens-csd** [rinukkusu/darksky-weather-dart#3]
Just trying to use the plugin and there's a version conflict with the json_annotation version I'm using. Just wondering if you're going to release an upgrade? I'd be happy to post a patch if it would help. 

"Because darksky_weather >=1.1.0 depends on json_annotation ^2.0.0 and yourapp depends on json_annotation ^3.0.0, darksky_weather >=1.1.0 is forbidden."

**Comment by rinukkusu** [comment]
Hi, sadly I only have my smartphone with me for the next two weeks. I'd appreciate a pull request - I can also merge it then. You'd need to reference this github instead of the package Version until I'm able to publish to pub, though. :)

**Comment by sowens-csd** [comment]
Thanks for the quick answer!

Just put one through. Note that I updated the package version to 1.3.0 since this makes it incompatible for users of 1.2.0 if they haven't upgraded to the later json_annotation yet. Let me know if you have any questions.

**Comment by rinukkusu** [comment]
Hey, I've merged your PR. I assume nothing has changed regarding the annotations themselves. 

Thanks for helping out - I will push to pub as soon as I get back from vacation :)

**Comment by sowens-csd** [comment]
Thanks for the quick turnaround. Sorry to intrude on vacation. I've seen no changes in the annotations across the two plugins and one app I've upgraded so far.

**Comment by sowens-csd** [comment]
Happy almost 2020! I haven't seen an update to the published version on pub.dev. Just curious if you're planning to do a release there? 

If / when you do. I think there might be an issue with the way you're including your dependencies. When importing classes from Darksky there are two separate paths for the same classes. It shows up if you browse the API docs from pub.dev as well. You can see the issue here https://pub.dev/documentation/darksky_weather/latest/ which shows two copies of the same class. You might want to resolve that if you're going to do a release.

**Comment by itsyaasir** [comment]
Hi @sowens-csd and @rinukkusu  I've been trying to work with this library . I wanted to use the values of var forecast in my weather app text values , and I couldn't figure it out how to extract the forecast out of the function. Please can you guide me on how to use for filling in text fields ?I'm using it in flutter
`Text(
                  '${darkSky.}°',
                  style: TextStyle(
                    fontSize: 100.0,
                    color: kMyColor,
                  ),
                ),`

**Comment by sowens-csd** [comment]
First off you need a forecast, you might already have one but you've used `darkSky` for the var name above which implies that maybe you just have the API entry point and not a forecast. To get a forecast you use the `getForecast` method for a particular lat/long:
```dart
Forecast _forecast = await _darkSky.getForecast(_lat, _long);
```
Then, to get the text summary from a forecast, for example, you'd use 
```dart
'${forecast.currently.summary}'
```
Given the text you have above looks like maybe you're looking for a temperature? If so you'd probably want:
```dart
'${forecast.currently.temperature}'
```

**Comment by indigo-dev** [comment]
I would be more than happy to see the current release on official pub.dev

**Comment by rinukkusu** [comment]
Hi, I've published the new version on pub.dev - sorry for the long wait!!
