### ISSUE TITLE
Feature request: getting flags and alerts from json

### ISSUE THREAD

**Issue by DanielSmith1239** [rinukkusu/darksky-weather-dart#5]
Can you add in alerts and flags from the json response? They are listed in [the Dark Sky documentation](https://darksky.net/dev/docs), but I don't see any way to get them from your API. Thanks!

**Comment by DanielSmith1239** [comment]
I'm dumb, figured out how to do it.

**Comment by DanielSmith1239** [comment]
I was a bit confused before, now I don't see the option to retrieve alerts.

**Comment by rinukkusu** [comment]
Your wish is my command - flags and alerts are now present in v1.4.0. I hope, everything works as expected, implemented it in a hurry. :)

**Comment by DanielSmith1239** [comment]
Thanks, really appreciate it. I’m using your api in my app “Rain: Simple Weather Forecast”, and I wanted to add alerts.

**Comment by rinukkusu** [comment]
lol @ the review section of your Google Play app entry. 😸
