### ISSUE TITLE
Package only to web

### ISSUE THREAD

**Issue by deandreamatias** [rinukkusu/darksky-weather-dart#6]
Hi,
Why in pub.dev this package is only avaliable to flutter/web and dart/js? 
![image](https://user-images.githubusercontent.com/21011641/75792292-06cb6480-5d6e-11ea-9efb-f8fc698f13fb.png)

I guess you can make/check avaliable to flutter/mobile and dart/native.

Thanks

**Comment by rinukkusu** [comment]
Hi @deandreamatias I'm not sure why it says that but pretty convinced that it works both in native and mobile with the "io" version of the package.
```dart
// For flutter and native
import 'package:darksky_weather/darksky_weather_io.dart';
// For web
import 'package:darksky_weather/darksky_weather.dart';
```
