### ISSUE TITLE
Need to regenerate generated code

### ISSUE THREAD

**Issue by RyanRamchandar** [rinukkusu/darksky-weather-dart#8]
The json definition was updated in #7 but the generated code was not regenerated. The following files need to be regenerated:
```
lib/darksky_weather_browser.g.dart
lib/darksky_weather_io.g.dart
```

I tried doing this myself, but I updated Flutter to 1.2.0, and I'm running in to https://github.com/google/json_serializable.dart/issues/684

**Comment by rinukkusu** [comment]
Yeah, totally forgot about regenerating these haha - `1.4.1+1` published!

**Comment by RyanRamchandar** [comment]
No worries! Thanks for the quick turn around.
