### ISSUE TITLE
Please update for daily

### ISSUE THREAD

**Issue by abgrano** [rinukkusu/darksky-weather-dart#9]
time: 1602432000,
summary: "Rain until evening.",
icon: "rain",
sunriseTime: 1602454980,
sunsetTime: 1602498540,
moonPhase: 0.84,
precipIntensity: 0.0232,
precipIntensityMax: 0.071,
precipIntensityMaxTime: 1602432000,
precipProbability: 0.93,
precipType: "rain",
temperatureHigh: 88.49,
temperatureHighTime: 1602482580,
temperatureLow: 74.75,
temperatureLowTime: 1602538920,
apparentTemperatureHigh: 102.42,
apparentTemperatureHighTime: 1602482460,
apparentTemperatureLow: 77.14,
apparentTemperatureLowTime: 1602538860,
dewPoint: 76.52,
humidity: 0.9,
pressure: 1007.8,
windSpeed: 4.37,
windGust: 17.13,
windGustTime: 1602462060,
windBearing: 173,
cloudCover: 0.99,
uvIndex: 5,
uvIndexTime: 1602477060,
visibility: 8.58,
ozone: 261,
temperatureMin: 74.79,
temperatureMinTime: 1602453120,
temperatureMax: 88.49,
temperatureMaxTime: 1602482580,
apparentTemperatureMin: 77.09,
apparentTemperatureMinTime: 1602453060,
apparentTemperatureMax: 102.42,
apparentTemperatureMaxTime: 1602482460

**Comment by rinukkusu** [comment]
Hi, what do you mean?
